# Generated by Django 4.2.7 on 2023-11-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='Fotos')),
                ('nome', models.CharField(max_length=250)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=200)),
                ('contato', models.CharField(max_length=11)),
            ],
        ),
    ]
